AsciiComments:
  Enabled: false
Style/FileName:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/SpaceInsideBrackets:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
