#!/bin/bash -x
# create synbolic link to ~/ for dotfiles
# memo: use `unlink` to delete symlink

files=`find .* -maxdepth 0 -type f`
dir=`pwd`

for f in $files; do
  ln -sf $dir/$f $HOME;
done

ln -sf $dir/.doom.d $HOME/.doom.d
